/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  InternshipExperience as PrismaInternshipExperience,
} from "@prisma/client";

export class InternshipExperienceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.InternshipExperienceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.internshipExperience.count(args);
  }

  async internshipExperiences(
    args: Prisma.InternshipExperienceFindManyArgs
  ): Promise<PrismaInternshipExperience[]> {
    return this.prisma.internshipExperience.findMany(args);
  }
  async internshipExperience(
    args: Prisma.InternshipExperienceFindUniqueArgs
  ): Promise<PrismaInternshipExperience | null> {
    return this.prisma.internshipExperience.findUnique(args);
  }
  async createInternshipExperience(
    args: Prisma.InternshipExperienceCreateArgs
  ): Promise<PrismaInternshipExperience> {
    return this.prisma.internshipExperience.create(args);
  }
  async updateInternshipExperience(
    args: Prisma.InternshipExperienceUpdateArgs
  ): Promise<PrismaInternshipExperience> {
    return this.prisma.internshipExperience.update(args);
  }
  async deleteInternshipExperience(
    args: Prisma.InternshipExperienceDeleteArgs
  ): Promise<PrismaInternshipExperience> {
    return this.prisma.internshipExperience.delete(args);
  }
}
